# -*- coding: utf-8 -*-
"""Actividad Clase Bloomberg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnOlD1E7IJ2Ji_dUWREk50BFdiD74LHL
"""

import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings('ignore', category=UserWarning)
warnings.filterwarnings('ignore', category=FutureWarning)

# Upload Excel files
print("Please upload Bloomberg_1min Excel file")
upload_1min = files.upload()
filename_1min = list(upload_1min.keys())[0]
df_1min = pd.read_excel(filename_1min)

print("Please upload Bloomberg_3min Excel file")
upload_3min = files.upload()
filename_3min = list(upload_3min.keys())[0]
df_3min = pd.read_excel(filename_3min)

# Print available columns
print("\nBloomberg_1min DataFrame columns:", list(df_1min.columns))
print("Bloomberg_3min DataFrame columns:", list(df_3min.columns))

# Define column names for closing prices
jpm_column = "JPM Close"
goog_column = "GOOG Close"
nvda_column = "NVDA Close"

# Extract closing prices for both time frequencies
try:
    jpm_1min = df_1min[jpm_column].dropna()
    goog_1min = df_1min[goog_column].dropna()
    nvda_1min = df_1min[nvda_column].dropna()
    jpm_3min = df_3min[jpm_column].dropna()
    goog_3min = df_3min[goog_column].dropna()
    nvda_3min = df_3min[nvda_column].dropna()
except KeyError as e:
    print(f"Error: Column {e} not found in one or both DataFrames")
    print("Please ensure the Excel files contain columns: 'JPM Close', 'GOOG Close', 'NVDA Close'")
    raise

# Ensure series have the same length for each frequency
min_length_1min = min(len(jpm_1min), len(goog_1min), len(nvda_1min))
jpm_1min = jpm_1min[:min_length_1min]
goog_1min = goog_1min[:min_length_1min]
nvda_1min = nvda_1min[:min_length_1min]

min_length_3min = min(len(jpm_3min), len(goog_3min), len(nvda_3min))
jpm_3min = jpm_3min[:min_length_3min]
goog_3min = goog_3min[:min_length_3min]
nvda_3min = nvda_3min[:min_length_3min]

# Function for unit root tests with detailed interpretation
def unit_root_tests(series, name, freq):
    print(f"\nUnit Root Tests for {name} ({freq}):")

    # ADF Test
    adf_result = adfuller(series, autolag='AIC')
    print("ADF Test:")
    print(f'  Statistic: {adf_result[0]:.4f}')
    print(f'  p-value: {adf_result[1]:.4f}')
    print(f'  Critical Values: {adf_result[4]}')
    print("  Interpretation:")
    if adf_result[1] < 0.05:
        print(f"    - p-value < 0.05: Reject null hypothesis - {name} is likely stationary")
        print(f"    - Implication: No differencing may be needed for ARIMA modeling.")
    else:
        print(f"    - p-value >= 0.05: Fail to reject null - {name} is likely non-stationary")
        print(f"    - Implication: Differencing may be required for ARIMA modeling.")

    # KPSS Test
    kpss_result = kpss(series, regression='c')
    print("\nKPSS Test:")
    print(f'  Statistic: {kpss_result[0]:.4f}')
    print(f'  p-value: {kpss_result[1]:.4f}')
    print(f'  Critical Values: {kpss_result[3]}')
    print("  Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"    - p-value < 0.05: Reject null hypothesis - {name} is likely non-stationary")
        print(f"    - Implication: Confirms need for differencing or trend adjustment.")
    else:
        print(f"    - p-value >= 0.05: Fail to reject null - {name} is likely stationary")
        print(f"    - Implication: Series may be suitable for modeling without differencing.")

    # Combined interpretation
    print("  Combined Interpretation:")
    if adf_result[1] < 0.05 and kpss_result[1] >= 0.05:
        print(f"    - {name} is stationary (both tests agree).")
    elif adf_result[1] >= 0.05 and kpss_result[1] < 0.05:
        print(f"    - {name} is non-stationary (both tests agree).")
    else:
        print(f"    - Tests conflict. Consider differencing or further analysis.")

# Cointegration test using Johansen test
def cointegration_test(df, name1, name2, freq):
    try:
        result = coint_johansen(df, det_order=0, k_ar_diff=1)
        print(f"\nJohansen Cointegration Test for {name1} vs {name2} ({freq}):")
        print(f"  Trace Statistic: {result.lr1}")
        print(f"  Critical Values (90%, 95%, 99%): {result.cvt}")
        print("  Interpretation:")
        for i in range(len(result.lr1)):
            if result.lr1[i] > result.cvt[i, 1]:
                print(f"    - r = {i}: Cointegration at 95% confidence level")
                print(f"      Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
            else:
                print(f"    - r = {i}: No cointegration at 95% confidence level")
                print(f"      Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")
        print("  Implication:")
        if result.lr1[0] > result.cvt[0, 1]:
            print(f"    - {name1} and {name2} are likely cointegrated.")
            print(f"    - Implication: A long-run equilibrium relationship exists, suitable for error correction models.")
        else:
            print(f"    - No evidence of cointegration between {name1} and {name2}.")
            print(f"    - Implication: Independent ARIMA models are appropriate.")
    except Exception as e:
        print(f"  Error in cointegration test: {e}")
        print(f"  Implication: Cointegration analysis inconclusive; proceed with independent models.")

# Function to find best ARIMA model
def find_best_arima(series, name, freq, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA Model for {name} ({freq}):")
    print(f"  Order: {best_order}")
    print(f"  AIC: {best_aic:.2f}")
    print("  Interpretation:")
    print(f"    - p={best_order[0]}: {best_order[0]} autoregressive term(s) capture past value effects.")
    print(f"    - d={best_order[1]}: {best_order[1]} difference(s) achieve stationarity.")
    print(f"    - q={best_order[2]}: {best_order[2]} moving average term(s) model past errors.")
    print(f"    - Implication: Model balances fit and complexity for forecasting.")
    return best_order

# Function to plot forecasts with confidence intervals and residuals
def plot_forecast(model, series, name, freq, steps=30):
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    forecast_index = range(len(series), len(series) + steps)

    # Forecast plot
    plt.figure(figsize=(12, 6))
    plt.plot(series.index, series, label=f'{name} Historical', color='blue')
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.fill_between(forecast_index,
                     conf_int.iloc[:, 0],
                     conf_int.iloc[:, 1],
                     color='pink', alpha=0.3,
                     label='95% Confidence Interval')
    plt.title(f'{name} Price Forecast ({freq})')
    plt.xlabel('Time Index')
    plt.ylabel('Price')
    plt.legend()
    plt.grid(True)
    plt.show()

    # Residuals plot
    residuals = model.resid
    plt.figure(figsize=(12, 6))
    plt.plot(residuals, label='Residuals')
    plt.axhline(0, color='black', linestyle='--', alpha=0.5)
    plt.title(f'Residuals of ARIMA Model for {name} ({freq})')
    plt.xlabel('Time Index')
    plt.ylabel('Residuals')
    plt.legend()
    plt.grid(True)
    plt.show()

    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    forecast_change = mean_forecast - last_value
    conf_int_width = conf_int.iloc[-1, 1] - conf_int.iloc[-1, 0]

    print(f"\nForecast Interpretation for {name} ({freq}):")
    print(f"  Last observed value: {last_value:.2f}")
    print(f"  Average forecast value: {mean_forecast:.2f}")
    print(f"  Forecast change: {forecast_change:.2f}")
    print(f"  Trend: {'Upward' if forecast_change > 0 else 'Downward' if forecast_change < 0 else 'Flat'}")
    print(f"  95% CI at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")
    print(f"  CI width: {conf_int_width:.2f}")
    print("  Implication:")
    if conf_int_width > abs(forecast_change):
        print(f"    - Wide CI suggests high forecast uncertainty.")
    else:
        print(f"    - Narrow CI suggests reliable forecast.")
    if abs(forecast_change) > series.std():
        print(f"    - Forecast change is significant relative to historical volatility.")
    else:
        print(f"    - Forecast change is within typical historical variation.")

    # Residuals interpretation
    resid_mean = residuals.mean()
    resid_std = residuals.std()
    print(f"  Residuals Analysis:")
    print(f"    - Mean: {resid_mean:.4f}")
    print(f"    - Standard Deviation: {resid_std:.4f}")
    print("    - Implication:")
    if abs(resid_mean) < resid_std:
        print(f"      - Residuals are centered around zero, indicating unbiased model.")
    else:
        print(f"      - Non-zero mean residuals suggest potential model bias.")
    if resid_std > series.std() / 10:
        print(f"      - High residual volatility indicates model may not capture all patterns.")
    else:
        print(f"      - Low residual volatility suggests good model fit.")

    return forecast[:5]

# Process data for each frequency
data_sets = [
    ('1min', jpm_1min, goog_1min, nvda_1min),
    ('3min', jpm_3min, goog_3min, nvda_3min)
]

for freq, jpm_series, goog_series, nvda_series in data_sets:
    print(f"\n=== Processing {freq} Data ===")

    # Unit root tests
    unit_root_tests(jpm_series, "JPM", freq)
    unit_root_tests(goog_series, "GOOG", freq)
    unit_root_tests(nvda_series, "NVDA", freq)

    # Cointegration tests
    coint_df_jpm_goog = pd.DataFrame({'JPM': jpm_series, 'GOOG': goog_series}).dropna()
    coint_df_goog_nvda = pd.DataFrame({'GOOG': goog_series, 'NVDA': nvda_series}).dropna()
    cointegration_test(coint_df_jpm_goog, "JPM", "GOOG", freq)
    cointegration_test(coint_df_goog_nvda, "GOOG", "NVDA", freq)

    # ARIMA models and forecasts
    print(f"\nModeling and Forecasting for {freq}:")
    jpm_order = find_best_arima(jpm_series, "JPM", freq)
    jpm_model = ARIMA(jpm_series, order=jpm_order).fit()
    jpm_forecast = plot_forecast(jpm_model, jpm_series, "JPM", freq)

    goog_order = find_best_arima(goog_series, "GOOG", freq)
    goog_model = ARIMA(goog_series, order=goog_order).fit()
    goog_forecast = plot_forecast(goog_model, goog_series, "GOOG", freq)

    nvda_order = find_best_arima(nvda_series, "NVDA", freq)
    nvda_model = ARIMA(nvda_series, order=nvda_order).fit()
    nvda_forecast = plot_forecast(nvda_model, nvda_series, "NVDA", freq)

    # Print forecast values
    print(f"\nJPM Forecast Values (first 5 periods, {freq}):")
    print(jpm_forecast)
    print(f"\nGOOG Forecast Values (first 5 periods, {freq}):")
    print(goog_forecast)
    print(f"\nNVDA Forecast Values (first 5 periods, {freq}):")
    print(nvda_forecast)

# Combined forecast plot
plt.figure(figsize=(14, 10))
for freq, jpm_series, goog_series, nvda_series in data_sets:
    # Use simplified ARIMA orders for combined plot to reduce computation
    jpm_order = find_best_arima(jpm_series, "JPM", freq, max_p=1, max_d=1, max_q=1)
    goog_order = find_best_arima(goog_series, "GOOG", freq, max_p=1, max_d=1, max_q=1)
    nvda_order = find_best_arima(nvda_series, "NVDA", freq, max_p=1, max_d=1, max_q=1)

    jpm_model = ARIMA(jpm_series, order=jpm_order).fit()
    goog_model = ARIMA(goog_series, order=goog_order).fit()
    nvda_model = ARIMA(nvda_series, order=nvda_order).fit()

    jpm_forecast = jpm_model.forecast(steps=30)
    goog_forecast = goog_model.forecast(steps=30)
    nvda_forecast = nvda_model.forecast(steps=30)
    forecast_index = range(len(jpm_series), len(jpm_series) + 30)

    plt.plot(jpm_series.index, jpm_series, label=f'JPM Historical ({freq})', alpha=0.5)
    plt.plot(forecast_index, jpm_forecast, label=f'JPM Forecast ({freq})', linestyle='--')
    plt.plot(goog_series.index, goog_series, label=f'GOOG Historical ({freq})', alpha=0.5)
    plt.plot(forecast_index, goog_forecast, label=f'GOOG Forecast ({freq})', linestyle='--')
    plt.plot(nvda_series.index, nvda_series, label=f'NVDA Historical ({freq})', alpha=0.5)
    plt.plot(forecast_index, nvda_forecast, label=f'NVDA Forecast ({freq})', linestyle='--')

plt.title('JPM, GOOG, NVDA Closing Prices with Forecasts (1min & 3min)')
plt.xlabel('Time Index')
plt.ylabel('Price')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

# Final Results Interpretation
print("\n=== Final Results Interpretation ===")
print("1. Stationarity Analysis:")
print("   - ADF and KPSS tests indicate whether each series requires differencing.")
print("   - Stationary series (p < 0.05 for ADF, p >= 0.05 for KPSS) are ideal for ARIMA.")
print("   - Non-stationary series may need d > 0 in ARIMA models.")

print("\n2. Cointegration Analysis:")
print("   - Cointegration between pairs (JPM-GOOG, GOOG-NVDA) suggests long-run relationships.")
print("   - If cointegrated, consider vector error correction models for improved forecasting.")
print("   - If not cointegrated, independent ARIMA models are appropriate.")

print("\n3. ARIMA Modeling:")
print("   - Best models selected based on AIC minimize complexity while fitting data.")
print("   - p, d, q parameters reflect autoregressive, differencing, and moving average components.")
print("   - Residual analysis validates model fit (low mean, stable variance).")

print("\n4. Forecasting:")
print("   - 30-period forecasts provide short-term price expectations.")
print("   - Confidence intervals quantify uncertainty; wider CIs indicate less reliable forecasts.")
print("   - Forecast trends (upward/downward) guide investment decisions.")
print("   - Compare 1min and 3min results to assess time-frequency impacts.")

print("\n5. Practical Implications:")
print("   - Use forecasts for trading strategies, but consider CI width for risk.")
print("   - Non-stationary series or high residual volatility may require model refinement.")
print("   - Cointegration results can inform pair trading or portfolio strategies.")
print("   - Validate forecasts with out-of-sample testing for robustness.")