# -*- coding: utf-8 -*-
"""Evidencia Situación problema Series Tiempo - Capital Analyst

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyivxLWiy1V8RRa5J1eEcM5FMBkM1K5k
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, kpss, coint
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import warnings
import itertools
from pathlib import Path
import openpyxl
import base64
import io
from IPython.display import display, Image

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")

# Define stocks, time intervals, and column name for closing prices
stocks = ['PG', 'MSFT', 'CAT']
intervals = ['5minutes', '30minutes']
close_column = 'Close'  # Confirmed column name
date_column = 'Local Date'  # Confirmed date column name
data_dir = Path('.')  # Directory containing Excel files
default_sheet_name = 'Sheet 1'  # Confirmed sheet name

# List to store plot data (title and base64-encoded image)
plot_data = []

# Function to save plot to base64 string and display inline
def save_plot_to_base64_and_show():
    buf = io.BytesIO()
    plt.savefig(buf, format='png', bbox_inches='tight')
    buf.seek(0)
    img_base64 = base64.b64encode(buf.getvalue()).decode('utf-8')
    display(Image(buf.getvalue()))  # Display plot inline in Colab
    buf.close()
    plt.close()
    return img_base64

# Function to get sheet names from an Excel file
def get_sheet_names(file_path):
    try:
        workbook = openpyxl.load_workbook(file_path)
        return workbook.sheetnames
    except Exception as e:
        print(f"Error reading sheet names from {file_path}: {e}")
        return []

# Function to load data
def load_data(stock, interval):
    file_path = data_dir / f'{stock}_{interval}.xlsx'
    if not file_path.exists():
        print(f"File {file_path} not found.")
        return None

    # Get all sheet names
    sheet_names = get_sheet_names(file_path)
    print(f"\nSheet names in {file_path}: {sheet_names}")
    if not sheet_names:
        print(f"No sheets found in {file_path}.")
        return None

    # Try the default sheet name first
    try:
        df = pd.read_excel(file_path, engine='openpyxl', sheet_name=default_sheet_name, header=0, parse_dates=[date_column])
        df = df.set_index(date_column)  # Set 'Local Date' as the index
        print(f"\nLoaded {file_path} (Sheet: {default_sheet_name}):")
        print(f"Columns: {list(df.columns)}")
        print(f"First few rows:\n{df.head()}")
        if close_column not in df.columns:
            print(f"'{close_column}' column not found in {default_sheet_name}.")
            return try_other_sheets(file_path, sheet_names)
        return df[close_column].dropna()
    except ValueError as e:
        print(f"Error reading {default_sheet_name} from {file_path}: {e}")
        return try_other_sheets(file_path, sheet_names)
    except Exception as e:
        print(f"Unexpected error reading {file_path}: {e}")
        return None

# Function to try other sheets if default sheet fails
def try_other_sheets(file_path, sheet_names):
    for sheet in sheet_names:
        try:
            df = pd.read_excel(file_path, engine='openpyxl', sheet_name=sheet, header=0, parse_dates=[date_column])
            df = df.set_index(date_column)  # Set 'Local Date' as the index
            print(f"\nTrying sheet {sheet} in {file_path}:")
            print(f"Columns: {list(df.columns)}")
            print(f"First few rows:\n{df.head()}")
            if close_column in df.columns:
                print(f"Found '{close_column}' in sheet {sheet}.")
                return df[close_column].dropna()
            else:
                print(f"'{close_column}' column not found in sheet {sheet}.")
        except Exception as e:
            print(f"Error reading sheet {sheet} from {file_path}: {e}")
    print(f"No sheet in {file_path} contains '{close_column}' column.")
    return None

# Random walk test (variance ratio test approximation)
def random_walk_test(series, name, interval):
    print(f"\nRandom Walk Test for {name} ({interval}):")
    returns = series.pct_change().dropna()
    var_1 = returns.var()
    aggregated = series.resample('4T' if '5minutes' in interval else '4H').last().pct_change().dropna()
    var_agg = aggregated.var()
    ratio = var_agg / (4 * var_1)
    print(f"Variance Ratio: {ratio:.4f}")
    print("Ratio ≈ 1 suggests random walk behavior.")

    # Plot original and aggregated series
    plt.figure(figsize=(10, 6))
    plt.plot(series, label='Original Series', alpha=0.7)
    plt.plot(aggregated.index, aggregated * series.mean(), label='Aggregated Series (scaled)', linestyle='--')  # Scale for visibility
    plt.title(f'{name} ({interval}) - Random Walk Test')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - Random Walk Test', save_plot_to_base64_and_show()))

# ADF test for stationarity
def adf_test(series, name, interval):
    print(f"\nADF Test for {name} ({interval}):")
    result = adfuller(series, autolag='AIC')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    if result[1] < 0.05:
        print("Series is likely stationary (reject null of unit root).")
    else:
        print("Series is likely non-stationary (fail to reject unit root).")

    # Plot series and differences
    plt.figure(figsize=(10, 6))
    plt.subplot(2, 1, 1)
    plt.plot(series, label='Original Series')
    plt.title(f'{name} ({interval}) - ADF Test: Original Series')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()

    plt.subplot(2, 1, 2)
    diff_series = series.diff().dropna()
    plt.plot(diff_series, label='First Difference', color='orange')
    plt.title('First Difference')
    plt.xlabel('Date')
    plt.ylabel('Price Difference')
    plt.legend()
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - ADF Test', save_plot_to_base64_and_show()))

# KPSS test for stationarity
def kpss_test(series, name, interval):
    print(f"\nKPSS Test for {name} ({interval}):")
    statistic, p_value, lags, crit = kpss(series, regression='c', nlags='auto')
    print(f'KPSS Statistic: {statistic:.4f}')
    print(f'p-value: {p_value:.4f}')
    print(f'Critical Values: {crit}')
    if p_value < 0.05:
        print("Series is likely non-stationary (reject null of stationarity).")
    else:
        print("Series is likely stationary (fail to reject stationarity).")

    # Plot series and differences
    plt.figure(figsize=(10, 6))
    plt.subplot(2, 1, 1)
    plt.plot(series, label='Original Series')
    plt.title(f'{name} ({interval}) - KPSS Test: Original Series')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()

    plt.subplot(2, 1, 2)
    diff_series = series.diff().dropna()
    plt.plot(diff_series, label='First Difference', color='orange')
    plt.title('First Difference')
    plt.xlabel('Date')
    plt.ylabel('Price Difference')
    plt.legend()
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - KPSS Test', save_plot_to_base64_and_show()))

# Cointegration test
def cointegration_test(series1, series2, series3, names, interval):
    print(f"\nCointegration Test ({interval}):")
    pairs = [(0, 1), (0, 2), (1, 2)]
    for i, j in pairs:
        s1 = series1
        s2 = series2 if i == 0 and j == 1 else series3
        name1, name2 = names[i], names[j]
        score, p_value, _ = coint(s1, s2, trend='c')
        print(f"{name1} vs {name2}: p-value = {p_value:.4f}")
        if p_value < 0.05:
            print(f"Evidence of cointegration between {name1} and {name2}.")
        else:
            print(f"No evidence of cointegration between {name1} and {name2}.")

        # Plot series and spread
        plt.figure(figsize=(10, 6))
        plt.subplot(2, 1, 1)
        plt.plot(s1, label=name1)
        plt.plot(s2, label=name2)
        plt.title(f'{name1} vs {name2} ({interval}) - Cointegration Test')
        plt.xlabel('Date')
        plt.ylabel('Price')
        plt.legend()

        plt.subplot(2, 1, 2)
        spread = s1 - s2  # Simple difference as a proxy for spread
        plt.plot(spread, label='Spread', color='purple')
        plt.title('Spread (Difference)')
        plt.xlabel('Date')
        plt.ylabel('Price Difference')
        plt.legend()
        plt.tight_layout()
        plot_data.append((f'{name1} vs {name2} ({interval}) - Cointegration Test', save_plot_to_base64_and_show()))

# AR model fitting
def fit_ar(series, name, interval):
    print(f"\nAR Model Fitting for {name} ({interval}):")
    result = adfuller(series)
    data = series
    if result[1] >= 0.05:
        print("Series is non-stationary; applying differencing for AR model.")
        data = series.diff().dropna()

    best_aic = float("inf")
    best_lag = None
    best_model = None

    for lag in range(1, 4):
        try:
            model = AutoReg(data, lags=lag)
            results = model.fit()
            aic = results.aic
            if aic < best_aic:
                best_aic = aic
                best_lag = lag
                best_model = results
        except:
            continue

    if best_model is None:
        print("No suitable AR model found.")
        return

    print(f"Best AR({best_lag}) model: AIC = {best_aic:.2f}")
    print(best_model.summary())

    # Plot diagnostics
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    axes[0, 0].plot(best_model.resid)
    axes[0, 0].set_title('Residuals')
    plot_acf(best_model.resid, ax=axes[0, 1])
    plot_pacf(best_model.resid, ax=axes[1, 0])
    axes[1, 1].hist(best_model.resid, bins=30)
    axes[1, 1].set_title('Residual Histogram')
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - AR({best_lag}) Diagnostics', save_plot_to_base64_and_show()))

    # Plot fitted values
    plt.figure(figsize=(10, 6))
    plt.plot(data, label='Actual')
    plt.plot(best_model.fittedvalues, label='Fitted', linestyle='--')
    plt.title(f'{name} ({interval}) - AR({best_lag}) Fit')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - AR({best_lag}) Fit', save_plot_to_base64_and_show()))

# ARMA model fitting
def fit_arma(series, name, interval):
    print(f"\nARMA Model Fitting for {name} ({interval}):")
    result = adfuller(series)
    data = series
    if result[1] >= 0.05:
        print("Series is non-stationary; applying differencing for ARMA model.")
        data = series.diff().dropna()

    p = q = range(0, 3)
    pq = list(itertools.product(p, q))
    best_aic = float("inf")
    best_order = None
    best_model = None

    for param in pq:
        try:
            model = ARIMA(data, order=(param[0], 0, param[1]))
            results = model.fit()
            aic = results.aic
            if aic < best_aic:
                best_aic = aic
                best_order = (param[0], 0, param[1])
                best_model = results
        except:
            continue

    if best_model is None:
        print("No suitable ARMA model found.")
        return

    print(f"Best ARMA{best_order} model: AIC = {best_aic:.2f}")
    print(best_model.summary())

    # Plot diagnostics
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    axes[0, 0].plot(best_model.resid)
    axes[0, 0].set_title('Residuals')
    plot_acf(best_model.resid, ax=axes[0, 1])
    plot_pacf(best_model.resid, ax=axes[1, 0])
    axes[1, 1].hist(best_model.resid, bins=30)
    axes[1, 1].set_title('Residual Histogram')
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - ARMA{best_order} Diagnostics', save_plot_to_base64_and_show()))

    # Plot fitted values
    plt.figure(figsize=(10, 6))
    plt.plot(data, label='Actual')
    plt.plot(best_model.fittedvalues, label='Fitted', linestyle='--')
    plt.title(f'{name} ({interval}) - ARMA{best_order} Fit')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - ARMA{best_order} Fit', save_plot_to_base64_and_show()))

# ARIMA model fitting
def fit_arima(series, name, interval):
    print(f"\nARIMA Model Fitting for {name} ({interval}):")
    result = adfuller(series)
    diff_series = series
    d = 0
    if result[1] >= 0.05:
        print("Series is non-stationary; applying differencing.")
        diff_series = series.diff().dropna()
        d = 1
        result = adfuller(diff_series)
        if result[1] >= 0.05:
            diff_series = diff_series.diff().dropna()
            d = 2

    p = q = range(0, 3)
    pdq = list(itertools.product(p, [d], q))
    best_aic = float("inf")
    best_order = None
    best_model = None

    for param in pdq:
        try:
            model = ARIMA(series, order=param)
            results = model.fit()
            aic = results.aic
            if aic < best_aic:
                best_aic = aic
                best_order = param
                best_model = results
        except:
            continue

    if best_model is None:
        print("No suitable ARIMA model found.")
        return

    print(f"Best ARIMA{best_order} model: AIC = {best_aic:.2f}")
    print(best_model.summary())

    # Plot diagnostics
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    axes[0, 0].plot(best_model.resid)
    axes[0, 0].set_title('Residuals')
    plot_acf(best_model.resid, ax=axes[0, 1])
    plot_pacf(best_model.resid, ax=axes[1, 0])
    axes[1, 1].hist(best_model.resid, bins=30)
    axes[1, 1].set_title('Residual Histogram')
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - ARIMA{best_order} Diagnostics', save_plot_to_base64_and_show()))

    # Plot fitted values
    plt.figure(figsize=(10, 6))
    plt.plot(series, label='Actual')
    plt.plot(best_model.fittedvalues, label='Fitted', linestyle='--')
    plt.title(f'{name} ({interval}) - ARIMA{best_order} Fit')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.tight_layout()
    plot_data.append((f'{name} ({interval}) - ARIMA{best_order} Fit', save_plot_to_base64_and_show()))

# Function to create HTML report
def create_html_report(plot_data):
    html_content = """
    <html>
    <head>
        <title>Stock Analysis Report</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { text-align: center; }
            h2 { color: #333; }
            img { max-width: 100%; height: auto; margin: 10px 0; }
        </style>
    </head>
    <body>
        <h1>Stock Analysis Report</h1>
    """

    for interval in intervals:
        html_content += f"<h2>{interval} Interval</h2>"
        for stock in stocks:
            html_content += f"<h3>{stock}</h3>"
            for title, img_base64 in plot_data:
                if stock in title and interval in title:
                    html_content += f"<h4>{title}</h4>"
                    html_content += f'<img src="data:image/png;base64,{img_base64}" alt="{title}">'
        # Add cointegration plots
        html_content += f"<h3>Cointegration Tests</h3>"
        for title, img_base64 in plot_data:
            if 'Cointegration' in title and interval in title:
                html_content += f"<h4>{title}</h4>"
                html_content += f'<img src="data:image/png;base64,{img_base64}" alt="{title}">'

    html_content += """
    </body>
    </html>
    """

    with open('EVIDENCE_CODE.html', 'w') as f:
        f.write(html_content)
    print("\nHTML report generated: EVIDENCE_CODE.html")

# Main analysis loop
for interval in intervals:
    print(f"\n=== Analysis for {interval} Interval ===")
    data = {}
    for stock in stocks:
        series = load_data(stock, interval)
        if series is None:
            continue
        data[stock] = series

    # Align series by common timestamps
    if len(data) == 3:
        print("\nAligning series by common timestamps:")
        for stock in stocks:
            print(f"{stock} series length: {len(data[stock])}")
        # Combine series into a DataFrame and keep only common timestamps
        aligned_data = pd.concat([data['PG'], data['MSFT'], data['CAT']], axis=1, keys=stocks)
        aligned_data = aligned_data.dropna()  # Keep only rows with data for all stocks
        print(f"Aligned data length: {len(aligned_data)}")
        data['PG'] = aligned_data['PG']
        data['MSFT'] = aligned_data['MSFT']
        data['CAT'] = aligned_data['CAT']

    for stock in stocks:
        if stock in data:
            series = data[stock]
            random_walk_test(series, stock, interval)
            adf_test(series, stock, interval)
            kpss_test(series, stock, interval)
            fit_ar(series, stock, interval)
            fit_arma(series, stock, interval)
            fit_arima(series, stock, interval)

    if len(data) == 3:
        cointegration_test(data['PG'], data['MSFT'], data['CAT'], stocks, interval)

# Generate HTML report with all plots
create_html_report(plot_data)