# -*- coding: utf-8 -*-
"""Pregunta 18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZszJbGNqMsydEmNJSneJDU6lGX3lofc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, kpss
import warnings
import base64
import io

warnings.filterwarnings("ignore")

# Reading the Excel file (assumes file is uploaded to Colab)
df = pd.read_excel("21.1_Q18.xlsx")

# Extracting the time and money columns
time = df['TIME']
money = np.array(df['MONEY'])

# Function to convert plot to base64-encoded string
def plot_to_base64():
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    img_str = base64.b64encode(buffer.getvalue()).decode('utf-8')
    buffer.close()
    return img_str

# Function to perform ADF test for stationarity
def adf_test(series, title=''):
    result = adfuller(series, autolag='AIC')
    print(f'ADF Test on {title}')
    print(f'ADF Statistic: {result[0]}')
    print(f'p-value: {result[1]}')
    print('Critical Values:')
    for key, value in result[4].items():
        print(f'\t{key}: {value}')
    if result[1] <= 0.05:
        print("Strong evidence against null hypothesis, series is stationary.")
    else:
        print("Weak evidence against null hypothesis, series is non-stationary.")

# Function to perform KPSS test for stationarity
def kpss_test(series, title=''):
    result = kpss(series, regression='c', nlags='auto')
    print(f'\nKPSS Test on {title}')
    print(f'KPSS Statistic: {result[0]}')
    print(f'p-value: {result[1]}')
    print('Critical Values:')
    for key, value in result[3].items():
        print(f'\t{key}: {value}')
    if result[1] <= 0.05:
        print("Strong evidence against null hypothesis, series is non-stationary.")
    else:
        print("Weak evidence against null hypothesis, series is stationary.")

# Testing stationarity on original series
adf_test(money, 'M1 Money Supply')
kpss_test(money, 'M1 Money Supply')

# Differencing the series to achieve stationarity
money_diff = np.diff(money)
adf_test(money_diff, 'Differenced M1 Money Supply')
kpss_test(money_diff, 'Differenced M1 Money Supply')

# List to store base64-encoded images
img_base64_list = []

# 1. Random Walk Check (ARIMA(0,1,0))
random_walk_model = ARIMA(money, order=(0,1,0)).fit()
print('\nRandom Walk Model Summary:')
print(random_walk_model.summary())

# Plotting Random Walk
rw_fitted = random_walk_model.fittedvalues
plt.figure(figsize=(12,6))
plt.plot(time, money, label='Historical M1 Money Supply')
plt.plot(time, rw_fitted, label='Random Walk Fitted', color='green')
plt.title('Random Walk Model (ARIMA(0,1,0)) Fit')
plt.xlabel('Time (Months from Jan 1951)')
plt.ylabel('M1 Money Supply (Billions $)')
plt.legend()
plt.grid(True)
img_base64_list.append(plot_to_base64())
plt.show()
plt.close()

# 2. Unit Root Visualization (Original vs Differenced Series)
plt.figure(figsize=(12,6))
plt.subplot(2,1,1)
plt.plot(time, money, label='Original M1 Money Supply')
plt.title('Original M1 Money Supply (Unit Root Test)')
plt.xlabel('Time (Months from Jan 1951)')
plt.ylabel('Billions $')
plt.legend()
plt.grid(True)
plt.subplot(2,1,2)
plt.plot(time[1:], money_diff, label='Differenced M1 Money Supply', color='orange')
plt.title('Differenced Series (Stationary)')
plt.xlabel('Time (Months from Jan 1951)')
plt.ylabel('Change in Billions $')
plt.legend()
plt.grid(True)
plt.tight_layout()
img_base64_list.append(plot_to_base64())
plt.show()
plt.close()

# 3. Cointegration Note and Placeholder Plot
print('\nNote: Cointegration analysis requires at least two time series. '
      'Since only one series (M1 Money Supply) is provided, cointegration testing is not applicable.')
plt.figure(figsize=(12,6))
plt.text(0.5, 0.5, 'Cointegration Plot Not Applicable\n(Requires Multiple Time Series)',
         horizontalalignment='center', verticalalignment='center', fontsize=12)
plt.title('Cointegration Analysis')
plt.axis('off')
img_base64_list.append(plot_to_base64())
plt.show()
plt.close()

# 4. Fitting ARIMA model (p,d,q) = (1,1,1)
model = ARIMA(money, order=(1,1,1)).fit()
print('\nARIMA(1,1,1) Model Summary:')
print(model.summary())

# Forecasting 12 steps ahead
forecast_steps = 12
forecast = model.forecast(steps=forecast_steps)
forecast_index = np.arange(len(money), len(money) + forecast_steps)

# Plotting ARIMA Fit and Forecast
arima_fitted = model.fittedvalues
plt.figure(figsize=(12,6))
plt.plot(time, money, label='Historical M1 Money Supply')
plt.plot(time, arima_fitted, label='ARIMA(1,1,1) Fitted', color='purple')
plt.plot(forecast_index, forecast, label='Forecast', color='red')
plt.title('ARIMA(1,1,1) Model Fit and Forecast')
plt.xlabel('Time (Months from Jan 1951)')
plt.ylabel('M1 Money Supply (Billions $)')
plt.legend()
plt.grid(True)
img_base64_list.append(plot_to_base64())
plt.show()
plt.close()

# Creating HTML file with embedded images
html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>M1 Money Supply Analysis Plots</title>
</head>
<body>
    <h1>M1 Money Supply Analysis Plots</h1>
    <h2>Random Walk Model (ARIMA(0,1,0)) Fit</h2>
    <img src="data:image/png;base64,{}" alt="Random Walk Plot">
    <h2>Unit Root Test (Original vs Differenced Series)</h2>
    <img src="data:image/png;base64,{}" alt="Unit Root Plot">
    <h2>Cointegration Analysis</h2>
    <img src="data:image/png;base64,{}" alt="Cointegration Plot">
    <h2>ARIMA(1,1,1) Model Fit and Forecast</h2>
    <img src="data:image/png;base64,{}" alt="ARIMA Plot">
</body>
</html>
""".format(img_base64_list[0], img_base64_list[1], img_base64_list[2], img_base64_list[3])

# Writing HTML file
with open('forecast_plots.html', 'w') as f:
    f.write(html_content)

print("\nHTML file 'forecast_plots.html' has been created.")