# -*- coding: utf-8 -*-
"""Pregunta 19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZR-JxVJzlH1JE30qGLNYIGU5XzOb5fsp
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint

# Load the Excel file
df = pd.read_excel('Pregunta_19.xlsx', engine='openpyxl')

# Plot the two time series on the same graph
plt.figure(figsize=(10, 6))
plt.plot(df['obs'], df['GS3M'], label='GS3M')
plt.plot(df['obs'], df['GS6M'], label='GS6M')
plt.xlabel('Observation')
plt.ylabel('Values')
plt.title('Time Series Plot of GS3M and GS6M')
plt.legend()
plt.show()

# Perform ADF test for stationarity
adf_test_gs3m = adfuller(df['GS3M'])
adf_test_gs6m = adfuller(df['GS6M'])

# Plot ADF test results
fig, ax = plt.subplots(2, 1, figsize=(10, 12))

ax[0].plot(df['obs'], df['GS3M'], label='GS3M')
ax[0].set_title(f"ADF Test for GS3M: Test Statistic={adf_test_gs3m[0]}, p-value={adf_test_gs3m[1]}")
ax[0].legend()

ax[1].plot(df['obs'], df['GS6M'], label='GS6M')
ax[1].set_title(f"ADF Test for GS6M: Test Statistic={adf_test_gs6m[0]}, p-value={adf_test_gs6m[1]}")
ax[1].legend()

plt.show()

# Check for cointegration using Engle-Granger test
coint_test = coint(df['GS3M'], df['GS6M'])

# Plot cointegration test results
plt.figure(figsize=(10, 6))
plt.plot(df['obs'], df['GS3M'], label='GS3M')
plt.plot(df['obs'], df['GS6M'], label='GS6M')
plt.xlabel('Observation')
plt.ylabel('Values')
plt.title(f"Engle-Granger Cointegration Test: Test Statistic={coint_test[0]}, p-value={coint_test[1]}")
plt.legend()
plt.show()